/****** Object:  Database [Mediquei]    Script Date: 26/10/2021 09:26:37 ******/
USE [master]
GO
CREATE DATABASE [Mediquei]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Mediquei', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS01\MSSQL\DATA\Mediquei.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Mediquei_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS01\MSSQL\DATA\Mediquei.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Mediquei] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Mediquei].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Mediquei] SET ANSI_NULL_DEFAULT ON 
GO
ALTER DATABASE [Mediquei] SET ANSI_NULLS ON 
GO
ALTER DATABASE [Mediquei] SET ANSI_PADDING ON 
GO
ALTER DATABASE [Mediquei] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [Mediquei] SET ARITHABORT ON 
GO
ALTER DATABASE [Mediquei] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Mediquei] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Mediquei] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Mediquei] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Mediquei] SET CURSOR_DEFAULT  LOCAL 
GO
ALTER DATABASE [Mediquei] SET CONCAT_NULL_YIELDS_NULL ON 
GO
ALTER DATABASE [Mediquei] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Mediquei] SET QUOTED_IDENTIFIER ON 
GO
ALTER DATABASE [Mediquei] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Mediquei] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Mediquei] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Mediquei] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Mediquei] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Mediquei] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Mediquei] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Mediquei] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Mediquei] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Mediquei] SET RECOVERY FULL 
GO
ALTER DATABASE [Mediquei] SET  MULTI_USER 
GO
ALTER DATABASE [Mediquei] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Mediquei] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Mediquei] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Mediquei] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Mediquei] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Mediquei] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Mediquei] SET QUERY_STORE = OFF
GO
USE [Mediquei]
GO

CREATE TABLE Usuario (
UserName VARCHAR(50) PRIMARY KEY,
Password VARCHAR(20),
eMail VARCHAR(50),
eMailRecuperar VARCHAR(50)
)

CREATE TABLE Familiar (
codFamiliar INTEGER PRIMARY KEY,
nomeFamiliar VARCHAR(50),
UserName VARCHAR(50),
FOREIGN KEY(UserName) REFERENCES Usuario (UserName)
)

CREATE TABLE Cuidador (
codCuidador INTEGER PRIMARY KEY,
nomeCuidador VARCHAR(50),
UserName VARCHAR(50),
FOREIGN KEY(UserName) REFERENCES Usuario (UserName)
)

CREATE TABLE Remedio (
codRemedio INTEGER PRIMARY KEY,
farmaco VARCHAR(40),
detentor VARCHAR(40),
medicamento VARCHAR(40),
registroANS VARCHAR(50),
concentracao VARCHAR(20),
formaFarmaceutica VARCHAR(20)
)

CREATE TABLE Paciente (
codPaciente INTEGER PRIMARY KEY,
nomePaciente VARCHAR(30),
UserName VARCHAR(50),
codFamiliar1 INTEGER,
dataNascimento DATETIME,
FOREIGN KEY(UserName) REFERENCES Usuario (UserName),
FOREIGN KEY(codFamiliar1) REFERENCES Familiar (codFamiliar)
)

CREATE TABLE DesafioSaude (
codDesafio INTEGER PRIMARY KEY,
nomeDesafio VARCHAR(50)
)

CREATE TABLE Tratamento (
codPaciente INTEGER,
dataInicial DATETIME,
codDesafio INTEGER,
codRemedio INTEGER,
codEfeito1 INTEGER,
codEfeito2 INTEGER,
codEfeito3 INTEGER,
dataFinal DATETIME,
Observacao Text,
PRIMARY KEY(codPaciente,dataInicial,codDesafio,codRemedio),
FOREIGN KEY(codPaciente) REFERENCES Paciente (codPaciente),
FOREIGN KEY(codDesafio) REFERENCES DesafioSaude (codDesafio),
FOREIGN KEY(codRemedio) REFERENCES Remedio (codRemedio)
)

CREATE TABLE ContratoCuidador (
codPaciente INTEGER,
codCuidador INTEGER,
dataInicial DATETIME,
dataFinal DATETIME,
horaEntrada1 Time,
horaSaida1 time,
horaEntrada2 Time,
horaSaida2 Time,
PRIMARY KEY(codPaciente,codCuidador,dataInicial),
FOREIGN KEY(codPaciente) REFERENCES Paciente (codPaciente),
FOREIGN KEY(codCuidador) REFERENCES Cuidador (codCuidador)
)

CREATE TABLE EfeitoAdverso (
codEfeito INTEGER PRIMARY KEY,
descEfeito VARCHAR(50)
)

ALTER TABLE Tratamento ADD FOREIGN KEY(codEfeito1) REFERENCES EfeitoAdverso (codEfeito)
ALTER TABLE Tratamento ADD FOREIGN KEY(codEfeito2) REFERENCES EfeitoAdverso (codEfeito)
ALTER TABLE Tratamento ADD FOREIGN KEY(codEfeito3) REFERENCES EfeitoAdverso (codEfeito)